#!/usr/bin/env python3

import os
import sys

currentDirectory = os.path.dirname(os.path.abspath(__file__))
target = os.path.join(currentDirectory, "main", "setup-gct")
os.system(f"sudo chmod +x {target}")

check = True

try:
    sys.argv[1]
except IndexError:
    check = False

if(check):
    os.system(f"{target} {sys.argv[1]}")
else:
    os.system(f"{target}")