#!/usr/bin/env python3

import os
from time import sleep
from datetime import datetime
directory = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

os.system("sudo clear")
print("Checking ...")
sleep(1)
os.system("pip install simple-colors")
os.system("clear")
from simple_colors import *

directory_main = os.path.join(directory, 'main')
directory_cmb = os.path.join(directory, '.custom-macOs-bash')
directory_gclin = os.path.join(directory_main, 'gc-lin')
directory_trig = os.path.join(directory, '.customTRIGGERS')
directory_alloverVersion = os.path.join(directory, '.allover')

#time
now = datetime.now()
now = now.strftime("%B %d %H:%M:%S %Y")

print(magenta("Setup Sequence Activated ...", 'blink'))
# os.system("echo 'source ~/.custom-linux-bash' >> ~/.zshrc")
# os.system("echo 'junk log init `date`' > ~/.jLog")
# os.system("echo '~' >> ~/.jLog")
# os.system(f"sudo cp {directory_clb} ~/.custom-linux-bash")
# os.system(f"sudo cp {directory_gclin} ~/gc-lin")
with open(os.path.join(directory_main, 'setup-helper'), "w") as setup_helper:
    os.system("clear")
    print(yellow("Setup Sequence Activated."))
    print(yellow("Initializing setup-helper protocol ...", 'blink'))
    setup_helper.write("#!/usr/bin/env bash\n\n")
    setup_helper.write("clear")
    setup_helper.write("echo '\033[1;33mSetup Sequence Activated.\033[m'")
    setup_helper.write("echo '\033[1;33mInitialized setup-helper protocol.\033[m'")
    setup_helper.write("echo '\033[1;36mrunning setup helper protocol ...\033[m'")
    setup_helper.write("echo '\nsource ~/.custom-macOs-bash' >> ~/.zshrc\n")
    setup_helper.write("echo '\nsource ~/.customTRIGGERS' >> ~/.zshrc\n")
    setup_helper.write(f"echo 'junk log init {now}' > ~/.jLog\n")
    setup_helper.write("echo '~' >> ~/.jLog\n")
    setup_helper.write("sleep 2")
    setup_helper.write(f"sudo cp {directory_cmb} ~/.custom-linux-bash\n")
    setup_helper.write(f"sudo cp {directory_gclin} ~/gc-lin\n")
    setup_helper.write(f"sudo cp {directory_trig} ~/.customTRIGGERS\n")
    setup_helper.write(f"sudo cp {directory_alloverVersion} ~/.allover")
    os.system("clear")
    setup_helper.write("echo '\033[1;33mSetup Sequence Activated.\033[m'")
    setup_helper.write("echo '\033[1;33mInitialized setup-helper protocol.\033[m'")
    setup_helper.write("echo '\033[1;32msetup-helper protocol executed successfully.\033[m'")
    setup_helper.write("sleep 1")
    setup_helper.write("echo ''")
    setup_helper.write("echo '\033[1;34mfinalizing setup ...\033'")
os.system(f"sudo chmod +x {os.path.join(directory_main, 'setup-helper')}")
os.system(f"{os.path.join(directory_main, 'setup-helper')}")
os.system(f"rm -rf {os.path.join(directory_main, 'setup-helper')}")
sleep(2)
print(green("\nSetup Complete.", 'blink'))