#!/usr/bin/env python3

import os
from time import sleep
from datetime import datetime
directory = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

os.system("sudo clear")

directory_main = os.path.join(directory, 'main')
directory_clb = os.path.join(directory, '.custom-wsl-linux-bash')
directory_gclin = os.path.join(directory_main, 'gc-lin')
directory_alloverVersion = os.path.join(directory, '.allover')

#time
now = datetime.now()
now = now.strftime("%B %d %H:%M:%S %Y")

print("Setup Sequence Activated ...")
# os.system("echo 'source ~/.custom-linux-bash' >> ~/.zshrc")
# os.system("echo 'junk log init `date`' > ~/.jLog")
# os.system("echo '~' >> ~/.jLog")
# os.system(f"sudo cp {directory_clb} ~/.custom-linux-bash")
# os.system(f"sudo cp {directory_gclin} ~/gc-lin")
sleep(2)
with open(os.path.join(directory_main, 'setup-helper'), "w") as setup_helper:
    os.system("clear")
    print("Setup Sequence Activated.")
    print("Initializing setup-helper protocol ...")
    setup_helper.write("#!/usr/bin/env bash\n\n")
    setup_helper.write("clear\n")
    setup_helper.write("echo '\033[1;33mSetup Sequence Activated.\033[m'\n")
    setup_helper.write("sleep 2\n")
    setup_helper.write("echo '\033[1;33mInitialized setup-helper protocol.\033[m'\n")
    setup_helper.write("echo '\033[1;36mrunning setup helper protocol ...\033[m'\n")
    setup_helper.write("echo '\nsource ~/.custom-wsl-linux-bash' >> ~/.bashrc\n")
    setup_helper.write(f"echo 'junk log init {now}' > ~/.jLog\n")
    setup_helper.write("echo '~' >> ~/.jLog\n")
    setup_helper.write("user=`whoami`\n")
    setup_helper.write("sleep 2\n")
    setup_helper.write(f"sudo cp {directory_clb} ~/.custom-wsl-linux-bash\n")
    setup_helper.write(f"sudo cp {directory_gclin} ~/gc-lin\n")
    setup_helper.write(f"sudo cp {directory_alloverVersion} ~/.allover\n")
    setup_helper.write("sudo chown $user ~/.allover\n")
    os.system("clear")
    setup_helper.write("echo '\033[1;33mSetup Sequence Activated.\033[m'\n")
    setup_helper.write("echo '\033[1;33mInitialized setup-helper protocol.\033[m'\n")
    setup_helper.write("echo '\033[1;32msetup-helper protocol executed successfully.\033[m'\n")
    setup_helper.write("sleep 1\n")
    setup_helper.write("echo ''\n")
    setup_helper.write("echo '\033[1;34mfinalizing setup ...\033'\n")
os.system(f"sudo chmod +x {os.path.join(directory_main, 'setup-helper')}")
os.system(f"{os.path.join(directory_main, 'setup-helper')}")
os.system(f"rm -rf {os.path.join(directory_main, 'setup-helper')}")
sleep(2)
print("\nSetup Complete.")
